<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class DemoProductsSeeder extends Seeder
{
    public function run(): void
    {
        $cats = Category::pluck('id', 'slug');

        $products = [
            // ── MOTEUR ───────────────────────────────────────────────────────
            [
                'category_id'    => $cats['moteur'] ?? null,
                'sku'            => 'MTR-003',
                'oem_reference'  => '11101-75010',
                'name'           => 'Culasse Toyota Hilux 2.4 D',
                'slug'           => 'culasse-toyota-hilux-2-4-d',
                'description'    => 'Culasse d\'occasion pour Toyota Hilux moteur 2L diesel. Rectifiée et testée, sans fissure. Joints fournis.',
                'condition'      => 'refurbished',
                'price'          => 145.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['moteur'] ?? null,
                'sku'            => 'MTR-004',
                'oem_reference'  => '13502-54030',
                'name'           => 'Vilebrequin Toyota Corolla 1.8',
                'slug'           => 'vilebrequin-toyota-corolla-1-8',
                'description'    => 'Vilebrequin d\'occasion pour Toyota Corolla 1.8L (2002-2008). Cotes d\'origine, sans fissure, rectifié STD.',
                'condition'      => 'used_good',
                'price'          => 85.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['moteur'] ?? null,
                'sku'            => 'MTR-005',
                'oem_reference'  => null,
                'name'           => 'Carter huile moteur Peugeot 307 1.6 HDi',
                'slug'           => 'carter-huile-peugeot-307-1-6-hdi',
                'description'    => 'Carter d\'huile d\'occasion pour Peugeot 307 HDi 1.6. Propre, sans choc, bouchon de vidange intact.',
                'condition'      => 'used_good',
                'price'          => 18.00,
                'currency'       => 'EUR',
                'stock_quantity' => 3,
                'status'         => 'active',
            ],

            // ── FREINAGE ─────────────────────────────────────────────────────
            [
                'category_id'    => $cats['freinage'] ?? null,
                'sku'            => 'FRN-003',
                'oem_reference'  => '47201-12360',
                'name'           => 'Étrier de frein arrière Toyota Camry',
                'slug'           => 'etrier-frein-arriere-toyota-camry',
                'description'    => 'Étrier de frein arrière droit d\'occasion pour Toyota Camry. Piston non grippé, reconditionné avec kit joints neuf.',
                'condition'      => 'refurbished',
                'price'          => 35.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['freinage'] ?? null,
                'sku'            => 'FRN-004',
                'oem_reference'  => null,
                'name'           => 'Maître-cylindre frein Renault Logan',
                'slug'           => 'maitre-cylindre-frein-renault-logan',
                'description'    => 'Maître-cylindre de frein d\'occasion pour Renault Logan 1.4 / 1.6. Sans fuite, testé en pression.',
                'condition'      => 'used_good',
                'price'          => 28.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['freinage'] ?? null,
                'sku'            => 'FRN-005',
                'oem_reference'  => null,
                'name'           => 'Tambour de frein arrière Nissan Almera',
                'slug'           => 'tambour-frein-arriere-nissan-almera',
                'description'    => 'Tambour de frein arrière d\'occasion pour Nissan Almera. Non ovalisé, épaisseur conforme, vendu à l\'unité.',
                'condition'      => 'used_good',
                'price'          => 15.00,
                'currency'       => 'EUR',
                'stock_quantity' => 4,
                'status'         => 'active',
            ],

            // ── SUSPENSION ───────────────────────────────────────────────────
            [
                'category_id'    => $cats['suspension'] ?? null,
                'sku'            => 'SUS-002',
                'oem_reference'  => '48520-06260',
                'name'           => 'Amortisseur avant droit Toyota Camry XV40',
                'slug'           => 'amortisseur-avant-droit-toyota-camry-xv40',
                'description'    => 'Amortisseur avant droit d\'occasion pour Toyota Camry XV40 (2006-2011). Sans fuite d\'huile, test de rebond OK.',
                'condition'      => 'used_good',
                'price'          => 45.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['suspension'] ?? null,
                'sku'            => 'SUS-003',
                'oem_reference'  => null,
                'name'           => 'Triangle avant gauche Peugeot 308',
                'slug'           => 'triangle-avant-gauche-peugeot-308',
                'description'    => 'Triangle de suspension avant gauche d\'occasion pour Peugeot 308 (2007-2013). Silentblocs OK, rotule non usée.',
                'condition'      => 'used_good',
                'price'          => 30.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['suspension'] ?? null,
                'sku'            => 'SUS-004',
                'oem_reference'  => null,
                'name'           => 'Rotule de direction Toyota Prado 120',
                'slug'           => 'rotule-direction-toyota-prado-120',
                'description'    => 'Rotule de direction d\'occasion pour Toyota Land Cruiser Prado 120 (2002-2009). Jeu minimal, bague de protection intacte.',
                'condition'      => 'used_good',
                'price'          => 22.00,
                'currency'       => 'EUR',
                'stock_quantity' => 3,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['suspension'] ?? null,
                'sku'            => 'SUS-005',
                'oem_reference'  => null,
                'name'           => 'Barre stabilisatrice arrière BMW X5 E53',
                'slug'           => 'barre-stabilisatrice-arriere-bmw-x5-e53',
                'description'    => 'Barre stabilisatrice arrière d\'occasion pour BMW X5 E53 (2000-2006). Non vrillée, biellettes incluses.',
                'condition'      => 'used_good',
                'price'          => 50.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],

            // ── CARROSSERIE ──────────────────────────────────────────────────
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-001',
                'oem_reference'  => null,
                'name'           => 'Capot moteur Toyota Corolla E120',
                'slug'           => 'capot-moteur-toyota-corolla-e120',
                'description'    => 'Capot moteur d\'occasion pour Toyota Corolla E120 (2002-2007). Quelques rayures légères, sans accident, charnières intactes.',
                'condition'      => 'used_fair',
                'price'          => 55.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-002',
                'oem_reference'  => null,
                'name'           => 'Pare-chocs arrière Peugeot 307 SW',
                'slug'           => 'pare-chocs-arriere-peugeot-307-sw',
                'description'    => 'Pare-chocs arrière d\'occasion pour Peugeot 307 SW. Peint gris métallisé, sans fissure majeure.',
                'condition'      => 'used_good',
                'price'          => 38.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-003',
                'oem_reference'  => null,
                'name'           => 'Porte avant droite Renault Clio III',
                'slug'           => 'porte-avant-droite-renault-clio-iii',
                'description'    => 'Porte avant droite d\'occasion pour Renault Clio III (2005-2012). Peinte en blanc, vitre OK, mécanisme lève-vitre fonctionnel.',
                'condition'      => 'used_good',
                'price'          => 65.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-004',
                'oem_reference'  => null,
                'name'           => 'Aile avant gauche Nissan X-Trail T30',
                'slug'           => 'aile-avant-gauche-nissan-x-trail-t30',
                'description'    => 'Aile avant gauche d\'occasion pour Nissan X-Trail T30 (2001-2007). Sans impact majeur, prête à peindre.',
                'condition'      => 'used_fair',
                'price'          => 28.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-005',
                'oem_reference'  => null,
                'name'           => 'Rétroviseur extérieur gauche Toyota Hilux',
                'slug'           => 'retroviseur-exterieur-gauche-toyota-hilux',
                'description'    => 'Rétroviseur extérieur gauche d\'occasion pour Toyota Hilux (2005-2015). Glace OK, boîtier sans fissure, réglage électrique fonctionnel.',
                'condition'      => 'used_good',
                'price'          => 22.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],

            // ── ÉLECTRIQUE ───────────────────────────────────────────────────
            [
                'category_id'    => $cats['electrique'] ?? null,
                'sku'            => 'ELC-001',
                'oem_reference'  => '27060-0D021',
                'name'           => 'Alternateur Toyota Corolla 1.4 / 1.6',
                'slug'           => 'alternateur-toyota-corolla-1-4-1-6',
                'description'    => 'Alternateur d\'occasion pour Toyota Corolla 1.4/1.6 (2002-2010). Charge testée à 13,8V / 70A. Poulie et régulateur OK.',
                'condition'      => 'used_good',
                'price'          => 45.00,
                'currency'       => 'EUR',
                'stock_quantity' => 3,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['electrique'] ?? null,
                'sku'            => 'ELC-002',
                'oem_reference'  => null,
                'name'           => 'Démarreur Peugeot 206 / 307 1.4 HDi',
                'slug'           => 'demarreur-peugeot-206-307-1-4-hdi',
                'description'    => 'Démarreur d\'occasion pour Peugeot 206/307 1.4 HDi. Couple de démarrage testé, lanceur neuf monté.',
                'condition'      => 'refurbished',
                'price'          => 35.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['electrique'] ?? null,
                'sku'            => 'ELC-003',
                'oem_reference'  => null,
                'name'           => 'Calculateur moteur BMW Série 3 E46 318i',
                'slug'           => 'calculateur-moteur-bmw-serie-3-e46-318i',
                'description'    => 'Calculateur (ECU) d\'occasion pour BMW Série 3 E46 318i. Non antidémarré, prêt à reprogrammer.',
                'condition'      => 'used_good',
                'price'          => 99.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['electrique'] ?? null,
                'sku'            => 'ELC-004',
                'oem_reference'  => null,
                'name'           => 'Tableau de bord complet Toyota Hilux 2006',
                'slug'           => 'tableau-de-bord-toyota-hilux-2006',
                'description'    => 'Tableau de bord complet d\'occasion pour Toyota Hilux (2005-2008). Compteurs fonctionnels, rétroéclairage OK.',
                'condition'      => 'used_good',
                'price'          => 75.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['electrique'] ?? null,
                'sku'            => 'ELC-005',
                'oem_reference'  => null,
                'name'           => 'Capteur de position vilebrequin Renault Megane II',
                'slug'           => 'capteur-position-vilebrequin-renault-megane-ii',
                'description'    => 'Capteur PMH / vilebrequin d\'occasion pour Renault Megane II 1.6 / 1.9 dCi. Résistance mesurée conforme.',
                'condition'      => 'used_good',
                'price'          => 10.00,
                'currency'       => 'EUR',
                'stock_quantity' => 5,
                'status'         => 'active',
            ],

            // ── TRANSMISSION ─────────────────────────────────────────────────
            [
                'category_id'    => $cats['transmission'] ?? null,
                'sku'            => 'TRS-001',
                'oem_reference'  => null,
                'name'           => 'Boîte de vitesses manuelle Toyota Corolla 1.6',
                'slug'           => 'boite-vitesses-manuelle-toyota-corolla-1-6',
                'description'    => 'Boîte de vitesses manuelle 5 rapports d\'occasion pour Toyota Corolla 1.6 (2002-2010). Passage engrenages propre, sans bruit anormal.',
                'condition'      => 'used_good',
                'price'          => 275.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['transmission'] ?? null,
                'sku'            => 'TRS-002',
                'oem_reference'  => '43420-12310',
                'name'           => 'Demi-arbre de transmission avant Toyota Corolla',
                'slug'           => 'demi-arbre-transmission-avant-toyota-corolla',
                'description'    => 'Demi-arbre côté boîte d\'occasion pour Toyota Corolla (2002-2010). Soufflets intacts, pas de claquement à l\'accélération.',
                'condition'      => 'used_good',
                'price'          => 38.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['transmission'] ?? null,
                'sku'            => 'TRS-003',
                'oem_reference'  => null,
                'name'           => 'Différentiel arrière Nissan Patrol Y60',
                'slug'           => 'differentiel-arriere-nissan-patrol-y60',
                'description'    => 'Différentiel arrière complet d\'occasion pour Nissan Patrol Y60. Sans bruit en rotation, huile propre à vider.',
                'condition'      => 'used_good',
                'price'          => 145.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['transmission'] ?? null,
                'sku'            => 'TRS-004',
                'oem_reference'  => null,
                'name'           => 'Kit embrayage Peugeot 307 1.6 HDi',
                'slug'           => 'kit-embrayage-peugeot-307-1-6-hdi',
                'description'    => 'Kit embrayage complet d\'occasion (disque + plateau + butée) pour Peugeot 307 1.6 HDi. Usage modéré, épaisseur disque 6mm.',
                'condition'      => 'used_fair',
                'price'          => 58.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['transmission'] ?? null,
                'sku'            => 'TRS-005',
                'oem_reference'  => null,
                'name'           => 'Cardan complet Toyota Land Cruiser 100',
                'slug'           => 'cardan-complet-toyota-land-cruiser-100',
                'description'    => 'Cardan de transmission d\'occasion pour Toyota Land Cruiser 100. Croisillons sans jeu, tubes sans torsion.',
                'condition'      => 'used_good',
                'price'          => 110.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],

            // ── REFROIDISSEMENT ──────────────────────────────────────────────
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-001',
                'oem_reference'  => '16400-0D060',
                'name'           => 'Radiateur eau Toyota Corolla 1.4 / 1.6',
                'slug'           => 'radiateur-eau-toyota-corolla-1-4-1-6',
                'description'    => 'Radiateur eau d\'occasion pour Toyota Corolla 1.4/1.6 (2002-2010). Test étanchéité OK, pas de fuite ni boue.',
                'condition'      => 'used_good',
                'price'          => 50.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-002',
                'oem_reference'  => null,
                'name'           => 'Pompe à eau Toyota Hilux 2.5 D4D',
                'slug'           => 'pompe-eau-toyota-hilux-2-5-d4d',
                'description'    => 'Pompe à eau d\'occasion pour Toyota Hilux 2.5 D4D. Sans jeu sur l\'axe, joint d\'origine en bon état.',
                'condition'      => 'used_good',
                'price'          => 25.00,
                'currency'       => 'EUR',
                'stock_quantity' => 3,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-003',
                'oem_reference'  => null,
                'name'           => 'Thermostat moteur BMW Série 5 E60 525i',
                'slug'           => 'thermostat-moteur-bmw-serie-5-e60-525i',
                'description'    => 'Thermostat d\'occasion avec boîtier pour BMW Série 5 E60 525i. Ouverture vérifiée à 87°C, joint de boîtier inclus.',
                'condition'      => 'used_good',
                'price'          => 28.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-004',
                'oem_reference'  => null,
                'name'           => 'Ventilateur refroidissement électrique Peugeot 206',
                'slug'           => 'ventilateur-refroidissement-electrique-peugeot-206',
                'description'    => 'Motoventilateur électrique d\'occasion pour Peugeot 206 / 307. Moteur sans bruit, débit d\'air puissant, connecteur intact.',
                'condition'      => 'used_good',
                'price'          => 24.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-005',
                'oem_reference'  => null,
                'name'           => 'Réservoir expansion Mercedes Classe E W211',
                'slug'           => 'reservoir-expansion-mercedes-classe-e-w211',
                'description'    => 'Réservoir de liquide de refroidissement d\'occasion pour Mercedes-Benz Classe E W211. Sans fissure, bouchon et capteur de niveau inclus.',
                'condition'      => 'used_good',
                'price'          => 14.00,
                'currency'       => 'EUR',
                'stock_quantity' => 3,
                'status'         => 'active',
            ],
        ];

        foreach ($products as $data) {
            Product::firstOrCreate(['sku' => $data['sku']], $data);
        }
    }
}
