<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class DemoProductsSeeder extends Seeder
{
    public function run(): void
    {
        $cats = Category::pluck('id', 'slug');

        $products = [
            // ── MOTEUR ───────────────────────────────────────────────────────
            [
                'category_id'    => $cats['moteur'] ?? null,
                'sku'            => 'MTR-002',
                'oem_reference'  => 'A6510101520',
                'name'           => 'Vilebrequin Mercedes Classe E 220 CDI OM651',
                'slug'           => 'vilebrequin-mercedes-classe-e-220-cdi-om651',
                'description'    => 'Vilebrequin d\'occasion pour Mercedes-Benz Classe E 220 CDI OM651 (2009-2016). Cotes d\'origine, rectifié STD, sans fissure.',
                'condition'      => 'used_good',
                'price'          => 120.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['moteur'] ?? null,
                'sku'            => 'MTR-003',
                'oem_reference'  => 'A2720101420',
                'name'           => 'Carter d\'huile Mercedes Classe C 180 CGI W204',
                'slug'           => 'carter-huile-mercedes-classe-c-180-cgi-w204',
                'description'    => 'Carter d\'huile d\'occasion pour Mercedes-Benz Classe C 180 CGI W204 (2007-2014). Propre, sans choc ni fissure.',
                'condition'      => 'used_good',
                'price'          => 32.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['moteur'] ?? null,
                'sku'            => 'MTR-004',
                'oem_reference'  => null,
                'name'           => 'Turbocompresseur Mercedes Sprinter 2.2 CDI 906',
                'slug'           => 'turbocompresseur-mercedes-sprinter-2-2-cdi-906',
                'description'    => 'Turbo d\'occasion pour Mercedes-Benz Sprinter 2.2 CDI (2006-2018). Axe sans jeu, turbine sans casse, testé en rotation.',
                'condition'      => 'refurbished',
                'price'          => 175.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['moteur'] ?? null,
                'sku'            => 'MTR-005',
                'oem_reference'  => 'A6420101505',
                'name'           => 'Jeu de segments moteur Mercedes GLE 350 CDI W166',
                'slug'           => 'segments-moteur-mercedes-gle-350-cdi-w166',
                'description'    => 'Jeu de segments moteur d\'occasion pour Mercedes-Benz GLE 350 CDI W166 (2015-2019). Cotes standards, testé et vérifié.',
                'condition'      => 'used_good',
                'price'          => 45.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],

            // ── FREINAGE ─────────────────────────────────────────────────────
            [
                'category_id'    => $cats['freinage'] ?? null,
                'sku'            => 'FRN-002',
                'oem_reference'  => 'A0004211212',
                'name'           => 'Maître-cylindre frein Mercedes Classe S W221',
                'slug'           => 'maitre-cylindre-frein-mercedes-classe-s-w221',
                'description'    => 'Maître-cylindre de frein d\'occasion pour Mercedes-Benz Classe S W221 (2005-2013). Sans fuite, testé en pression.',
                'condition'      => 'used_good',
                'price'          => 55.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['freinage'] ?? null,
                'sku'            => 'FRN-003',
                'oem_reference'  => null,
                'name'           => 'Disque de frein arrière Mercedes Classe E W211',
                'slug'           => 'disque-frein-arriere-mercedes-classe-e-w211',
                'description'    => 'Disque de frein arrière d\'occasion pour Mercedes-Benz Classe E W211 (2002-2009). Épaisseur conforme, vendu à l\'unité.',
                'condition'      => 'used_good',
                'price'          => 22.00,
                'currency'       => 'EUR',
                'stock_quantity' => 4,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['freinage'] ?? null,
                'sku'            => 'FRN-004',
                'oem_reference'  => null,
                'name'           => 'Plaquettes de frein avant Mercedes GLC W253',
                'slug'           => 'plaquettes-frein-avant-mercedes-glc-w253',
                'description'    => 'Plaquettes de frein avant d\'occasion pour Mercedes-Benz GLC W253 (2015-2022). Épaisseur restante 7mm. Bon état général.',
                'condition'      => 'used_good',
                'price'          => 18.00,
                'currency'       => 'EUR',
                'stock_quantity' => 3,
                'status'         => 'active',
            ],

            // ── SUSPENSION ───────────────────────────────────────────────────
            [
                'category_id'    => $cats['suspension'] ?? null,
                'sku'            => 'SUS-002',
                'oem_reference'  => 'A1663200030',
                'name'           => 'Amortisseur arrière droit Mercedes GLE W166',
                'slug'           => 'amortisseur-arriere-droit-mercedes-gle-w166',
                'description'    => 'Amortisseur arrière droit d\'occasion pour Mercedes-Benz GLE W166 (2015-2019). Sans fuite d\'huile, test de rebond OK.',
                'condition'      => 'used_good',
                'price'          => 75.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['suspension'] ?? null,
                'sku'            => 'SUS-003',
                'oem_reference'  => null,
                'name'           => 'Triangle avant gauche Mercedes Classe C W205',
                'slug'           => 'triangle-avant-gauche-mercedes-classe-c-w205',
                'description'    => 'Triangle de suspension avant gauche d\'occasion pour Mercedes-Benz Classe C W205 (2014-2021). Silentblocs OK, rotule non usée.',
                'condition'      => 'used_good',
                'price'          => 48.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['suspension'] ?? null,
                'sku'            => 'SUS-004',
                'oem_reference'  => null,
                'name'           => 'Rotule de direction Mercedes Sprinter W906',
                'slug'           => 'rotule-direction-mercedes-sprinter-w906',
                'description'    => 'Rotule de direction d\'occasion pour Mercedes-Benz Sprinter W906 (2006-2018). Jeu minimal, bague de protection intacte.',
                'condition'      => 'used_good',
                'price'          => 28.00,
                'currency'       => 'EUR',
                'stock_quantity' => 3,
                'status'         => 'active',
            ],

            // ── CARROSSERIE ──────────────────────────────────────────────────
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-001',
                'oem_reference'  => null,
                'name'           => 'Capot moteur Mercedes Classe C W204',
                'slug'           => 'capot-moteur-mercedes-classe-c-w204',
                'description'    => 'Capot moteur d\'occasion pour Mercedes-Benz Classe C W204 (2007-2014). Quelques rayures légères, sans accident, charnières intactes.',
                'condition'      => 'used_fair',
                'price'          => 90.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-002',
                'oem_reference'  => null,
                'name'           => 'Pare-chocs arrière Mercedes Classe E W212',
                'slug'           => 'pare-chocs-arriere-mercedes-classe-e-w212',
                'description'    => 'Pare-chocs arrière d\'occasion pour Mercedes-Benz Classe E W212 (2009-2016). Peint noir, sans fissure majeure.',
                'condition'      => 'used_good',
                'price'          => 65.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-003',
                'oem_reference'  => null,
                'name'           => 'Porte avant droite Mercedes Classe S W221',
                'slug'           => 'porte-avant-droite-mercedes-classe-s-w221',
                'description'    => 'Porte avant droite d\'occasion pour Mercedes-Benz Classe S W221 (2005-2013). Peinte en noir, vitre OK, mécanisme lève-vitre fonctionnel.',
                'condition'      => 'used_good',
                'price'          => 110.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-004',
                'oem_reference'  => null,
                'name'           => 'Aile avant gauche Mercedes GLE W166',
                'slug'           => 'aile-avant-gauche-mercedes-gle-w166',
                'description'    => 'Aile avant gauche d\'occasion pour Mercedes-Benz GLE W166 (2015-2019). Sans impact majeur, prête à peindre.',
                'condition'      => 'used_fair',
                'price'          => 55.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['carrosserie'] ?? null,
                'sku'            => 'CAR-005',
                'oem_reference'  => null,
                'name'           => 'Rétroviseur extérieur gauche Mercedes Sprinter W906',
                'slug'           => 'retroviseur-gauche-mercedes-sprinter-w906',
                'description'    => 'Rétroviseur extérieur gauche d\'occasion pour Mercedes-Benz Sprinter W906 (2006-2018). Glace OK, boîtier sans fissure, réglage électrique fonctionnel.',
                'condition'      => 'used_good',
                'price'          => 38.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],

            // ── ÉLECTRIQUE ───────────────────────────────────────────────────
            [
                'category_id'    => $cats['electrique'] ?? null,
                'sku'            => 'ELC-002',
                'oem_reference'  => 'A0001502280',
                'name'           => 'Démarreur Mercedes Classe C 220 CDI W204',
                'slug'           => 'demarreur-mercedes-classe-c-220-cdi-w204',
                'description'    => 'Démarreur d\'occasion pour Mercedes-Benz Classe C 220 CDI W204. Couple de démarrage testé, lanceur neuf monté.',
                'condition'      => 'refurbished',
                'price'          => 58.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['electrique'] ?? null,
                'sku'            => 'ELC-003',
                'oem_reference'  => null,
                'name'           => 'Calculateur moteur Mercedes GLE 350 CDI W166',
                'slug'           => 'calculateur-moteur-mercedes-gle-350-cdi-w166',
                'description'    => 'Calculateur (ECU) d\'occasion pour Mercedes-Benz GLE 350 CDI W166. Non antidémarré, prêt à reprogrammer.',
                'condition'      => 'used_good',
                'price'          => 145.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['electrique'] ?? null,
                'sku'            => 'ELC-004',
                'oem_reference'  => null,
                'name'           => 'Tableau de bord complet Mercedes Sprinter W906 2010',
                'slug'           => 'tableau-de-bord-mercedes-sprinter-w906-2010',
                'description'    => 'Tableau de bord complet d\'occasion pour Mercedes-Benz Sprinter W906 (2006-2018). Compteurs fonctionnels, rétroéclairage OK.',
                'condition'      => 'used_good',
                'price'          => 95.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['electrique'] ?? null,
                'sku'            => 'ELC-005',
                'oem_reference'  => 'A0041537828',
                'name'           => 'Capteur vilebrequin Mercedes Classe E W211 CDI',
                'slug'           => 'capteur-vilebrequin-mercedes-classe-e-w211-cdi',
                'description'    => 'Capteur PMH / vilebrequin d\'occasion pour Mercedes-Benz Classe E W211 CDI. Résistance mesurée conforme.',
                'condition'      => 'used_good',
                'price'          => 18.00,
                'currency'       => 'EUR',
                'stock_quantity' => 4,
                'status'         => 'active',
            ],

            // ── TRANSMISSION ─────────────────────────────────────────────────
            [
                'category_id'    => $cats['transmission'] ?? null,
                'sku'            => 'TRS-002',
                'oem_reference'  => 'A2512600600',
                'name'           => 'Demi-arbre de transmission avant Mercedes Classe C W205',
                'slug'           => 'demi-arbre-transmission-avant-mercedes-classe-c-w205',
                'description'    => 'Demi-arbre côté boîte d\'occasion pour Mercedes-Benz Classe C W205 (2014-2021). Soufflets intacts, pas de claquement à l\'accélération.',
                'condition'      => 'used_good',
                'price'          => 65.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['transmission'] ?? null,
                'sku'            => 'TRS-003',
                'oem_reference'  => null,
                'name'           => 'Différentiel arrière Mercedes GLE W166',
                'slug'           => 'differentiel-arriere-mercedes-gle-w166',
                'description'    => 'Différentiel arrière complet d\'occasion pour Mercedes-Benz GLE W166. Sans bruit en rotation, huile propre à vider.',
                'condition'      => 'used_good',
                'price'          => 225.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['transmission'] ?? null,
                'sku'            => 'TRS-004',
                'oem_reference'  => null,
                'name'           => 'Kit embrayage Mercedes Sprinter 2.2 CDI W906',
                'slug'           => 'kit-embrayage-mercedes-sprinter-2-2-cdi-w906',
                'description'    => 'Kit embrayage complet d\'occasion (disque + plateau + butée) pour Mercedes-Benz Sprinter 2.2 CDI W906. Usage modéré, épaisseur disque 7mm.',
                'condition'      => 'used_fair',
                'price'          => 80.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],

            // ── REFROIDISSEMENT ──────────────────────────────────────────────
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-001',
                'oem_reference'  => 'A2045000803',
                'name'           => 'Radiateur eau Mercedes Classe C W204',
                'slug'           => 'radiateur-eau-mercedes-classe-c-w204',
                'description'    => 'Radiateur eau d\'occasion pour Mercedes-Benz Classe C W204 (2007-2014). Test étanchéité OK, pas de fuite ni boue.',
                'condition'      => 'used_good',
                'price'          => 65.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-002',
                'oem_reference'  => 'A6512000104',
                'name'           => 'Pompe à eau Mercedes Classe E 220 CDI OM651',
                'slug'           => 'pompe-eau-mercedes-classe-e-220-cdi-om651',
                'description'    => 'Pompe à eau d\'occasion pour Mercedes-Benz Classe E 220 CDI OM651 (2009-2016). Sans jeu sur l\'axe, joint d\'origine en bon état.',
                'condition'      => 'used_good',
                'price'          => 35.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-003',
                'oem_reference'  => 'A6422030075',
                'name'           => 'Thermostat moteur Mercedes GLE 350 CDI W166',
                'slug'           => 'thermostat-moteur-mercedes-gle-350-cdi-w166',
                'description'    => 'Thermostat avec boîtier d\'occasion pour Mercedes-Benz GLE 350 CDI W166 (2015-2019). Ouverture vérifiée à 87°C, joint de boîtier inclus.',
                'condition'      => 'used_good',
                'price'          => 32.00,
                'currency'       => 'EUR',
                'stock_quantity' => 2,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-004',
                'oem_reference'  => null,
                'name'           => 'Motoventilateur électrique Mercedes Classe S W221',
                'slug'           => 'motoventilateur-electrique-mercedes-classe-s-w221',
                'description'    => 'Motoventilateur électrique d\'occasion pour Mercedes-Benz Classe S W221 (2005-2013). Moteur sans bruit, débit d\'air puissant, connecteur intact.',
                'condition'      => 'used_good',
                'price'          => 48.00,
                'currency'       => 'EUR',
                'stock_quantity' => 1,
                'status'         => 'active',
            ],
            [
                'category_id'    => $cats['refroidissement'] ?? null,
                'sku'            => 'REF-005',
                'oem_reference'  => 'A2115010015',
                'name'           => 'Réservoir expansion Mercedes Classe E W211',
                'slug'           => 'reservoir-expansion-mercedes-classe-e-w211',
                'description'    => 'Réservoir de liquide de refroidissement d\'occasion pour Mercedes-Benz Classe E W211 (2002-2009). Sans fissure, bouchon et capteur de niveau inclus.',
                'condition'      => 'used_good',
                'price'          => 14.00,
                'currency'       => 'EUR',
                'stock_quantity' => 3,
                'status'         => 'active',
            ],
        ];

        foreach ($products as $data) {
            Product::firstOrCreate(['sku' => $data['sku']], $data);
        }
    }
}
